spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 3000
#            request-interceptors:
#              - com.example.order.interceptor.XTokenRequestInterceptor
#            retryer: feign.Retryer.Default
feign:
  sentinel:
    enabled: true
