spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
      routes:
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: haha
#            - Vip=user,Spiral
            - name: Vip
              args:
                param: user
                value: Spiral
          order: 10
        - id: order-route
          uri: lb://service-order
          predicates:
#            - Path=/api/order/**
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          filters:  #/api/order/ab/c /ab/c
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
#            - AddResponseHeader=X-Response-Abc, 123
            - OnceToken=X-Response-Token, uuid
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters: #/api/order/ab/c /ab/c
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
          order: 2
      default-filters:
        - AddResponseHeader=X-Response-Abc, 123